### ISSUE TITLE
Wasn't able to run both versions 'File upload error' & asyncio.run() cannot be called from a running event loop (Solved) New issue : Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Yassine-El-M** [helallao/perplexity-ai#14]
Hi, thanks for this amazing code,
Unfortunately, I couldn't run the code 
The first version gives this error, the first error was not finding "myfile.txt" I had to create empty myfile.txt file to get this new error:

![image](https://github.com/helallao/perplexity-ai/assets/78159196/12545355-4e11-4060-b85a-80c0f8d97190)

For the Asynchronous Version, I get this error:

![image](https://github.com/helallao/perplexity-ai/assets/78159196/9b7c6ad4-2aaf-40dd-b3be-37f4b21e970d)

I'm not a professional in coding, a simple explanation would be much appreciated.
Thanks

**Comment by helallao** [comment]
File upload error is because of empty file, you need to write something inside it. Asynchronous version error may be because of your python version, im using python 3.11 and it has been major changes on asynchronous programming. https://stackoverflow.com/questions/55409641/asyncio-run-cannot-be-called-from-a-running-event-loop-when-using-jupyter-no

**Comment by Yassine-El-M** [comment]
![image](https://github.com/helallao/perplexity-ai/assets/78159196/57c1e707-14c2-417c-8696-94a401dfa2d3)


Thanks a lot for your help, regarding the second error, the solution that worked for me from the post you shared is :

import nest_asyncio
nest_asyncio.apply()

I put a query inside the txt file, but I still get the first error in both versions.

![image](https://github.com/helallao/perplexity-ai/assets/78159196/6ebf2757-e959-40d8-ab79-37aa2e1ceb6c)

**Comment by helallao** [comment]
First thing first, did you create an account? If you didn't you can't use file uploads. If you have created an account before asking a query and if it's still same, try to ask a query in copilot mode and control the "mode" key in response dictionary. If the key's value is "concise" then it shows us you can't ask questions in copilot mode. Renew your headers and cookies then try again.

**Comment by Yassine-El-M** [comment]
Thanks a lot, both versions are working now.
I had to use cookies after I log into Perplexity.
I know it sounds obvious to some experts, but laymen only follow instructions 😅


<img width="614" alt="image" src="https://github.com/helallao/perplexity-ai/assets/78159196/b91ee306-4441-4d28-b688-20b5b3a12ea5">

Thanks for your help
