### ISSUE TITLE
Error: Handshake status 400 Bad Request

### ISSUE THREAD

**Issue by PhanTask** [helallao/perplexity-ai#15]
I followed the tutorial but encountered `Error: Handshake status 400 Bad Request`. What could be the reason?

**Comment by PhanTask** [comment]
I noticed that when I click on "Sign Up" on perplexity.ai page, it is pending on the security checking page forever
```
www.perplexity.ai
Checking if the site connection is secure
www.perplexity.ai needs to review the security of your connection before proceeding.
```

Would this be the reason?

**Comment by helallao** [comment]
Huh, maybe you're blocked by cloudflare, because of sending too many requests. Just give it some time. You will be able to use the script when you be able to bypass cloudflare security check in browser.
