### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by PhanTask** [helallao/perplexity-ai#16]
I tried to use my own account to access (refer to https://github.com/helallao/perplexity-ai/issues/4), and I got this issue.

```
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
Cell In[2], line 1
----> 1 perplexity_cli = perplexity.Client(perplexity_headers, perplexity_cookies)

File ~/workspace/perplexity-ai-v2/perplexity.py:78, in Client.__init__(self, headers, cookies)
     76 self.t = format(random.getrandbits(32), '08x')
     77 print(self.session.get(f'[https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}').text[1](https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}%27).text[1):])
---> 78 self.sid = json.loads(self.session.get(f'[https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}').text[1:])['sid](https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}%27).text[1:])[%27sid)']
     79 self.frontend_uuid = str(uuid4())
     80 self.frontend_session_id = str(uuid4())

File ~/anaconda3/lib/python3.10/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    341     s = s.decode(detect_encoding(s), 'surrogatepass')
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:
    348     cls = JSONDecoder

File ~/anaconda3/lib/python3.10/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    332 def decode(self, s, _w=WHITESPACE.match):
    333     """Return the Python representation of ``s`` (a ``str`` instance
    334     containing a JSON document).
    335 
    336     """
--> 337     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338     end = _w(s, end).end()
    339     if end != len(s):

File ~/anaconda3/lib/python3.10/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I checked the content of `self.session.get(f'[https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}').text[1:]`:

`!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: "[www.perplexity.ai](https://www.perplexity.ai/)",cType: 'managed',cNounce: '24664',cRay: '806b2f80ac3c2889',cHash: '267f20784df18fd',cUPMDTk: "\/socket.io\/?EIO=4&transport=polling&t=d8480b84&__cf_chl_tk=FI0YS7VSAqP6oipLvZ1On93V3.LFqlPN2c2U1BFjGlU-1694721305-0-gaNycGzNEdA",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/socket.io\/?EIO=4&transport=polling&t=d8480b84&__cf_chl_f_tk=FI0YS7VSAqP6oipLvZ1On93V3.LFqlPN2c2U1BFjGlU-1694721305-0-gaNycGzNEdA",md: "msAU53hXn7ryEHJxDyqesgjprGXtYFGG5.MgO93uvT8-1694721305-0-Adl8ShJfFON5NRFT3-yr5p6EBXXTBKC52YImQaqZPz_1UXJLs2boOzubpzvuGw3qic8ZeM-0VBJYwrwlpj7q1vSp6j4pIFlkoZW1YC71fcsv-Tuyuve9ZgHiGc97C5x_KdgNljRW-ywxln9E1Ol0eSRq7OQp4v2hxaCemAiwyb5NRnkMQRIVKiIDcZDKSpJV7-D6kRmZm1MiOtQ2mC21_jszvbrRD2ZilNN7Uy1ocz6jSY3Ef1Xwz6yDM4JaYaRRzVqyWtuzsFNuloe7DUP0Gi66kT4jR7W2b6Rk3UpQ_BiUwcWfhFToib4dEjBLKZGmuRFy5dvZ-V-eTF812XPgpmzYoocVjWOz5rh7YEpHody3wlbXxLrGW7Ba-jeaourf-fUc7kv4dc7XhHW6nFkCrRuZtJhUbGMxDryQLWJuGYiyd8ubU8OIYVFOs198S-ZGuqnNLQuR2iXUTa6LeHPeZa2DK9-iWrSgXdh1T8GoOE_3p2BUnK-7_trgzCNuhuGt-aT5z_shTc1i3gIkwIwzhX-PEnMcKngiBdkZErPN8u5SXV_krvAm6dqfsUfidBiDIb6eH72Y0ouHvMOQl5gOUL-PUELb0oCckrIxwWVKJO19xCVXUERNfKRCa3mCNArKeHa-QO3bslJcpVk6vBccFhdK6QDr4BtJBII0g5qULmC2Y7liPjqaQWEthDMUDdgxRbR9v1a8W-sJrpPIDzK9JIZa2jSJ5f4BgN2__161ExSq_e12zfmql_hZ3unMWSSdzKt1SDhFuqQvp_ycr0cDjR6JgMKeHnqkWWFD3OaZffCJoaK4Bvzk_O4ilABi6ZHbSfEuzm0uvg9e6_X0Gu68WcJJuyzU9KSvYCKTiB9p7n4EYgFov85_iXQEnR3GGx4DdMzF5judz4aqjS1qPgGq0YJBEaU34y8pd6WU4xfNhEaH5pYIUBALb2znmzUVjvYXqL0-T4PX5Sg_Rne5Rd8fUnek3orygkLJx9YpXcc7Kao676MkwNMemcDLdrVKnJQbL3pLYQD8g04WkjPYS5NJrbZY_XM-jQn0dprz0lqMQQkSR594Tww6uBXargQHtYie_LjHQ4kTErk6u5S-AxzxBnTMfB7fFEoiqsG80JqZ8qZhZcOFnIhFSvw71CoytTJgNY9iu50HPxL68JF287e1DiztS2-ezAXStgF-iUqVnmONH7OJ-L7Zz4Ev_hl-hro-mkBtnFFDfkxwB4-u0cC9muRg5m1s3Z8q2kWZA6a6Q2Qn128Oq36aYtonMLdOtVfBKGJUQEw6YbvOzu211_zOJy9rFOQsNwPTC_aSyc1BjjjH3tGaLTgnBe1kLFeHsgcr4w6sXYKhE6eceat42gMZiXeZRSRmgLjVAUVuCgosw0tfaauaLV4t8JTowozsBgGWIhtxIiAs6uheFW_YADPe6GZSv8-gk9sAbmCNzcgyDBKBaKIde1kZQGHIn_xmQi6ZYoCCON7SGORRmDpB0le9LRjq7NzsOu56wMtszal3yfkjik9lvyqC4tesIXWZ9EXRw9fVsqa3ySYT3nNCSAzoX3cM9YQ4bK_JdPKl-zHf36ELmWDMSRgtaQ_4nK5Dw-MG7bdnaqA6fOq_MLj41whfow57-yXMkeLNNdcU5p-72maPcL9tyvYJoXLsSzggZILqAFUmeGBUhV3MtNsPvHPOcUUT-cxAYLWBpU_gKBnq4aw8IudK69ovBQe_fLM0a1gouKz_p3fKLeOoNLVHnx0f5670ZnR_IYmopo5YfKtAkkviA5MrnMvwtcApOSpYcw1RhewD0MYDrHzPMfMngsS6nONG-B1H1mShmvGlqYGsEGiqYarpWe1luJdtm0AVfeosyyDn2kXHwkc29KUoJqJQBcmryI8upaviqH-bQhQEYLQOZ0VJU50StLgBMWgJcSTegTKByJ3r4uD8ZMUTMRBzpFj9G5eG9Gxm0cXX5ilFGegOFLG4Diq32TNE4Mcwe9C8kW02fRffoyK-oYF46paewTKtRyzrWcJ5mdSgBwctkDktjegKLO4QkIMQbIMQs_hNDqwhrxcMcIDQ72hvusZu4KCn1qxhCmWWjtpQIy1V2r8xwc0a9ICHVfDcPlA91BWhx4DsBWy9xF-h6zVzAKC9ePP1gGmzWzJPjvMLyEbcv9RhUfu6ehDS7CfGNEC3jfQxSLHjcyQ-4nnjupa6pEWwOtmJoER1OO5T89m5OYWYuwcVxLy07fTAnC30Odl8VL9yd-XNGxo2x1K_uRfjURVvnAm1OOwZgvhIyqATO8qCfEQ4sZlePRWhgeAKm1_c5MW_dBrqX4TFXzkXh6vvmcHifpO9uuzXdokJfYRPb0wOiN9lpZzb7xO-3LCb6-XnzQqrwHWweQUzsbR0-y-8bu9qVVWLbz8AjtROul_9agzgssc6qy_xY0AiFfP5EbSi1kUMKPqmahYI9Y5f_ShA1laSsuOhXZI60ZCd-qn7PMwJo_i90jQQ8pAkjnD1TXI4fyc-1HpUk5QvMvKFkTqIVWVRwrFRtfM7taTOsmWdT90-Y_dGZV9sNz36bfSPIphxwCfhyzteGHqOpT--CGWYlV38CIWQebLRrCMSgLnkYRV4WWGaBUvB4TymLfbuLUNVoi4-L4sofrUVYI3y3kJ_jIPx3cIRyfEaboL2YqB8iHwNCVU_wWpm2TWF3h8jnvEV18T1zAqn1IkOxJ_g_WmCOTuPw8jd-I14Q_psiuE95mj4ov8iFsH3ekGNJ1kdyBe72XFDr4MVL1X-S5o2ldTjVlodbQ5U7DNfVU8kdkO-2-KUDGdbpAnPR3MnUAVNiJiHU2L5YLtX4euzbE21jYDcKu7d80admfpR87kZ9efH8jYN8A3PxFO9AWHpFGjwp_EEXDjQie0PiT1_XbIzHNkgidW54f6Z6TWQ3Pt9vE4KgcD0ad-1dQNi7ldrcHWtFq8ADN7tBwDzY3sfUfssZcWqtJjJ7aXzZ8gD3THfyuAAn7SYshjmUp4XPzqXYW22nqeeyMvpXyBRgS-v4ebBPvXem8tpz4rL_nINCaZB40enOSEANSgTJu8nLpPOFyDD-JAUV4k0T94tJsyUIOToumSVO7IAoCWfUfjPcLYHJVINvjlbC6tTiURvm5DxQ_EYN4tMYYMDXvPSTyH05q6U9VYIIbjpEpXzU0IiVSitYmmxP_Nyt6HIx58CXi-Gv0sD3P01EZYQQeG328orxMyjwla3KaGtB7uDlTyo4S9cMDzkXrevlevU8rGodR2jY-pB57gZMFOPoEbBDSLTd57CfydDjnASPWMwommcA85xcZg9Nub5U5jl6Z-kQ29VxYhM5a4UqDQOhJQoTqJkG7npz_nlksd-ye8es85HVfnk71gArZrEezk4k80n4yH_Jrr27ETazhefHCbFiBm814iP4keXnoU3qYnAPgrp_PkNtUhc7x23NePzbtAPTEVHFkQEMdxQTfx7qITYhfLCrJtf0X9vgqKtTTgnpeVoavs4gpgw28xR_or-4L6j75dI1HryZ4vqWBoIsbqlmIGEgP9qRVBE5-wOPnD0XHM0OTWHakJIbow9zsUxvCmT5K_c_8O9-oCA2KFGXr8z4zr-tdWChDp0gNqman44fOLSM3pw8cgOeW6TtFLY1W1p6iNPYdvd9_jAW7SK_VRAlWdKhJN_k7iFaowYJIy72fQd9F5R7ALaK-mYkd_JDhp_8FqP-MIiISJ5kSX9kSdMBpiRywgBs60SHeIVmUhAmrRUBPUKLg8wjz7IOdpgHd30Y_5PCiwb55D9R_Wt8RM1HBEK2vPn-6_HLQQ6QuYYf_f1LEWydqI4HrSiyUeaTIvEWA8EsnuUIF9BndmEeKfx_B_yYEyqzVzC0PYkv8qtcO-4TmbM_Ee7i4Xs7IQSP2ddvRAlerFIClM4p7J5A5fpRf965Ya-5FDdHNaZNFhShgBxaEmJBTY_75jzUt8sL7HHZpncy9oSVTJuhOWKwyhvA7Gk8paWOF1POk4Y997I_elDuedoj2IxPYJib3fk9yfc8YVLJPi44Vq7MB8m3TP3Ny00UOiKFrDgMT_1YjEW5N64UWthscdTm0XZ7_8faOqDPYhFH90JrHU462kVqynllXX0zY8xiw26pr59qYtEHquTrbwTX7ixKCzXhjxYTFop11iLPgV3qZEJFQ-mK_IeJ44s_LsalBgsvjyPOrQ_AlLs5Qr144pVuYguHhJuolnm0D4OgWQoK0KMywOsRon2p9lZBvawrjYNyvJ83sJE4dQ3lylkUfffnSBfyaSfr5TaVDnWVb7RhFVOFVSSdQTgusSm1yHb70N2mQgfHmuuq3_rnmjCAHUJyuzELvdNppRb0heGmciC8XhUaZQESNXap0xsUl6yNuI3FrGqBxIKXi4lQ_wrOiME43NrrfAAR5ovpN_maos5zisCyVbCJWj1cDxvfFkC1s6q7Txj9l-ePXsoQlbASGLrELJ8HzdeviNdCjonQiGYQRxxyiX5lTARSxj7c0Du8vX0iXZEPxE",cRq: {ru: 'aHR0cHM6Ly93d3cucGVycGxleGl0eS5haS9zb2NrZXQuaW8vP0VJTz00JnRyYW5zcG9ydD1wb2xsaW5nJnQ9ZDg0ODBiODQ=',ra: 'TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzExNy4wLjAuMCBTYWZhcmkvNTM3LjM2',rm: 'R0VU',d: 'Bv3LbKVcjrkuznaM49f8JoHYTAzqf2j9+0wqH3bJVGrG75fw5X0D2XOaft5kTEeWKqpG2chi6MBbUXNUTT4FGmu/K1r5YTf+4LyH46hKdovCp8g0xJkOCp+ul1unGnVEjANBEP05arcez7zhA0GXxE4UboN2UsHjbkqBPpgujuDRBSDczkNyW+B/miM2WsBGSzh7ZkGb0YOXvmHdPgM4QC4u8+KSN8m90KTwndN1bTDe7KjLl8zGoY7y3u/G0l+C7i+gbatdlFndi0rfgIuZUtdrunFZX6FJuEIDyVXp5C0478l02eVz6qgdIyq8s1k59bh+DGs5w4z/dHD+9ZbuSaySOqDmKh4gw7m50oWJ0jISSYqNKgeXhZe/b0B4b43exVu94bnyWmDH9tlKWDbVbY1MNaQSBqboeDuYhNref+2IXmbwHV3OjrTUfIBIdrYkzezYvp9sRcRIt+cdp6KMLruTZ0gWXH1Gc3W+Pn1BXjr0sdDWWksiul5Gdk9zeTpHYx89H90Riwo5OSIjODu5o2AnkTng9WdR0O2A8eVU76Lz2ZRbsx8IJWzI6jiy4+Dd',t: 'MTY5NDcyMTMwNS43MTgwMDA=',cT: Math.floor(Date.now() / 1000),m: 'FmdXWG+swhpuYNTAOifF+9naCD9KkyjhhSeay4IuBeo=',i1: 'jJX8TaNIoKjG3dkh5woZ/w==',i2: 'h69uOJUSvrdYjOS3VgQtHQ==',zh: 'NU8ixJjbvuzjjI0VYVlScfuo4FsYASw7wpJI5etvkPw=',uh: 'tZzwk0UXBB6aZMwUSrybzD1mMJwGI/1CIIfoh4RzeeI=',hh: 'Y4wbTy2+H//SzqXCr/ut8Fn8eNgcrMRWkXlJV1vMwRU=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=806b2f80ac3c2889';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/socket.io\/?EIO=4&transport=polling&t=d8480b84&__cf_chl_rt_tk=FI0YS7VSAqP6oipLvZ1On93V3.LFqlPN2c2U1BFjGlU-1694721305-0-gaNycGzNEdA" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854" integrity="sha512-bjgnUKX4azu3dLTVtie9u6TKqgx29RBwfj3QXYt5EKfWM/9hPSAI/4qcV5NACjwAo8UtTeWefx6Zq5PHcMm7Tg==" data-cf-beacon='{"rayId":"806b2f80ac3c2889","version":"2023.8.0","b":1,"token":"92730c73a9e747fbb6a25e1d6657122d","si":100}' crossorigin="anonymous"></script>`

It seems I cannot bypass cloudflare. This is the first time I use this script so I do not think it is because I sent too many requests. Could you please check if this also happens at your side? Would this be because they updated their firewall policy? Thanks.

**Comment by helallao** [comment]
No, it doesn't happen at my side
![image](https://github.com/helallao/perplexity-ai/assets/78656003/47457fb4-1e9b-4078-9db7-98833e2bc8d2)

Did you follow steps in issue #4 properly to use your own account as client?

**Comment by PhanTask** [comment]
@helallao Thanks for the reply! I changed to another network and it now works. It seems my company network was somehow blocked. I will close this issue now. Thanks again for the great project!
