### ISSUE TITLE
Unable to initialize Client class

### ISSUE THREAD

**Issue by The-Sal** [helallao/perplexity-ai#17]
Even with the latest headers the code raises the following stack trace:

File "~/PerplexityAI/_perplexity.py", line 72, in __init__
    self.sid = json.loads(self.session.get(f'https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}').text[1:])['sid']
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by helallao** [comment]
Tested it again and it works. Please follow the steps properly.

**Comment by The-Sal** [comment]
https://github.com/helallao/perplexity-ai/assets/70804343/9e8076e9-4929-49b3-a0d2-143b1663310f

Hi,
Thank you for responding. 
I think it maybe because I'm in Germany, a lot of my own scrapers stopped working because a lot of sites have a popup about data privacy, however I'm not sure if thats the exact problem.

**Comment by helallao** [comment]
If you're able to use perplexity in browser then you must be able to use it with perplexity.py, can you test are you able to use perplexity in browser?

**Comment by The-Sal** [comment]
Perplexity works in the browser just fine, i can query and get results normally

**Comment by helallao** [comment]
There must be something wrong, i can use perplexity.py with no problem.

**Comment by The-Sal** [comment]
So the get line `self.sid = json.loads(self.session.get(f'https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}').text[1:])['sid']` in the client init class when I checked it's output says `!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" rel="stylesheet"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '2',cZone: "www.perplexity.ai",cType: 'managed',cNounce: '22489',cRay: '8091f4cdb85254db',cHash: 'f83b4ab2b1f3c0d',cUPMDTk: "\/socket.io\/?EIO=4&transport=polling&t=39ee47e2&__cf_chl_tk=gU9S_66tXTTpluU4PM.qJJPFloDJ3sHCOgiuL4.D3NQ-1695127846-0-gaNycGzNEJA",cFPWv: 'b',cTTimeMs: '1000',cMTimeMs: '0',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/socket.io\/?EIO=4&transport=polling&t=39ee47e2&__cf_chl_f_tk=gU9S_66tXTTpluU4PM.qJJPFloDJ3sHCOgiuL4.D3NQ-1695127846-0-gaNycGzNEJA",md: "2Sjh4YXbJaDDaSa8E9.yK4y4DxSbPj91sX2Vd0oBXsg-1695127846-0-AUxAxjO-Toxm6JjT14f6rQvuVmhgeUU4YiKdUQAkgdmR2KK2hGXQM2Onx1uGNj8oM9ldWMUfmfV4pnbD6AIPmv43w_01YMsxsGhmMGzouThZ1x5Vh8VV1Fscmmm07N1UdZGhAZrInJ8BXJlCxmQ22_Vh78MW-1soRyOIpUlBRwT0TpKatzAGFRb62qcl1Gpbz4iDZxQWSDoQ3EYWdpDGXkXFS55wXmTDm5rFdJyf7lyifBsdNZ3ThcyuifwbnkM-OasxtYTxyzTDDA_yOrZMALH9y6yIMjm4hXAjJldoxROK4SJNcKV7nbAQTnbxX92MfxyXn7bRJJRfM3PKt8K2YEd6lQetswyiEHaAmlgnCklNiY57Zbyn8ZP07yt3NAiJJ6aUxGTAsZvP125IszZpL1Y7SdMcfHfej5lFH5iSKHHuWUKXFhcf-6t6FvYl8McSjvMj3g6T_tahcYVaQ8Wv2EuPzh9_j2Y_BjyOHOfk81vOiMc3dLtjZDvKtGF4S_tV1yvTjViFiYrC3dA52R_54IA03KmZlXjFW12LSsnOxxNWFr_cOsx7x__fVm08wO36a_BSbJjPFY2xgFA1qwLdhttiRYPYizReXzcrImcmwZVhUJNJzT7yA2arjMxfShQQ9jkXYWWz8CbXtjWPzbGkqiKrVrszrHfY-XODWJ3zxAf0M4Fewpiq1GpIePe3k7zCIJeNaxib6mnnITAxp7Yji1TlkEjOpC05s5tu2Msn-ltnjFw_z1XOzIsAqg9Qjk3A5gt-UunQX2dj_-iCOw3piddoZcJp_XeWZvysAziQ0TvHLNa50exr-I0dTd1T6FQI5JKCLEz9o9s1QJZG3Qd1UGibh34csuE01wOVMznQi1BZobJs1K45sun_B1ahKc8q9LivAgI8SwYBRFDjf031DbFOaKIC0H4OUgo2-WD0OsxWGSIoUuq41uhJTJQmKtcW3Af2BLFzWL4H2M2_vWT8010W6r5XecrM4SAqgDBSX4ixryXILdktoiALhhkSQhm0dUfQyMjEGbKk6oykGRpvjAqiZ30satYHqvoUbAnoBGI0y1MUeCnuBfEIhEbIjhrEOiZzRN7VbZpWRN3eBxGKqhc5q2SuZFqjM4Wk3V-3Xv1vR29m8p_vpLKAn_6qLWG6m1r7Vl3_r2rAGDaISBUyfNgRwJVCL84YpkrzJ_zUBR76zbAadDDW54MNz0wuX62PMYluEmesC_YwcheWDbG1LIv-Z6-L7ZYyDfr_DDFSH80UfBp9BF5Ta7nyHTQlSzW62wdDDzmenMshfQeJhe_hThsMjv9lsnq41a7n_5aJVzcWyTy78JMCuLkxhP0jRXyAymONbVbEOq6DRHXaiwUXUZ0bIhx7Ra2Th1dv5FOHZkOkYx_NF4kyOeec8uMAtwaNjjd4tPhqGhKnDGslwip3aBn_yO-8SnWby-NOxJx2EbvBNwx124L_mgQbdi2g6gmVPsuTJT7J7Zad7tKF_6uUN1EDj99jsToqpgfvMX-LC61nJcYug1ohsZNyNlMHKfmK8PL33RBXF3OQrZVwPhRc7N4fAwNzQ7-oAs_ZfxSfeTqrcswSN9188FFSg8isd1gkdosa3aCy0UBqPtRyb8IDePGrCyoictU4hQ9pJbrqIbTtwt30GtnT-fA1Oru4NQPGQcIGLj_-UZzDOhYfnJdEXj4IZut38ilfVF7ZKW4MDE1fgD3fl_pPGRVBSGK7l7-rLwnUFgONGH8atVEmurAWnkppOEhkAQPnF1NLNj768Dp2d2Q2wKx5HRenrrE81uSzzBxM3qWuBbTGMiNqSyds0D22wY8lC_tON2Nk5iFlPpVbh_v-hPexQjIPcdKTj0VfmhXg8nWrcuxb3kU1sFG2RugKnt9qZIvneIBJ5OKQSZTwyFdTvS5zgF5fV6oof8euBUdmAArKbzSvfr2dZH37fxOMqYJR0LdEIhkK0uqiDzvjR_6EgmtthwfBGxOye9ayKovGfjpe9ncKtxXLpYiajHEo_eqcZtc3Ig1hueIWipcCKmH1XOe4baZdwAAchhBCziSrODjVUGI9YHoqfOAObRyEPUYK-T4UpWC8S5l-hhh-CBU7wSJ_3X7DEYGzAHvGvnAvKBR03uDUFQzk82xbRshW30mS7yIVY4EACl6Qs2l-swPnTZ496PwIAGSfS3VWL6L_IRSSyg4Pyld_fnQcmh20Afi3uPg0kCGm4jyQPwCXbF8MfYqUNluaLzZiHq1-5MZYveUeLM6uygp0vQ6-l__vZLC2oLjwJBQmz5kYFK3sHtFm_MAMage3A1PPeiFOMPSAu4D5aWK3LEA-uVAbXTjm-nJ2AVFaQwYN4x7IcUdg0D8RRzmR9-4UuPXVzlS5iWxSDjGJ8P_oOA5RsXHsefATPtNFzGFwdJtl7zvAOBJl6yq9ixnBnnoMBcVnq8GlRnajO2BpHpOt8fCQcx9xsFTPeg66sWnZADU4Vzibe7pc_pmqg_lHNA_A3ZFOK1ctlTLPkNrz1oDp9BKrCR5wSVwumW0XOATc0HHLOa3GrHXj52hBU1MbnAUPJeS4vRZtvkQwE05acdwY4GrjAsbbVdeOxEmWOp02KLAolfNpSgtzXRd8SQPlD_TyAvaV1ZnOpm89bgJoqHr9UnuKHFmYjy3vD2VrVF6rU5tRZ2kCT3HSdnyffy8mKojshnzQQ5PPL6Yiv0IJilu47syADlqNUPpa5COJDfyViSerHnQ0JjiTv3qusa76Zc8GQBoqD1SWc7fDQX54U3JJLR-tVLuR3e_i3iFs8sb4qgkEBsr6F6aCqAINL29_GxwMPG7brB-65226o-_nvh63Pjt6gJ0TTdCEos8kkvIeh80j0sem6cBdemkQsQWSXSMxRKV22CkfJZLSx_P5JEr_7HMmhOHlfWdGck50bZ6z9SwovwDedu85ohNOMDyAigxifpFhywByL0hj8_q9MMKPfPRi72ovBa4v3FIN4uJKDlzDhhNromvhX0mk3MDTl0U7bzP_KyCTVq-0TFE0XNxlqh1mKYFSnhwU_y-vCxo8uWx8P8FPm9c__rnGtysiIyIyRUt7n2IendnZfJH0Xz3G-KOY2eps8PxmGuJonY_S8eZ3-3y5p6f0L8wtV7H1K07llPDyExJY1KoZrPzcWTiiCj-abSKC2qlRWzDkY9RNNG_rhjnYA96XfW2wWo_BtoBji-5m3K2kPXchkRrZRndrMCzlwS6rKiAwSl1Lef-oY2hFSf2cYWobqhGZ8B0fP7lyERXF4WfGOs38-i5hg1X1R9xAnIIv8OI8DqsgJiT54r5T49QGDk5wj-LjBa27DPLSqjTyqzxBACioYHDBDXrZHLSey3IndE-soUNx77yrU6GduGXawwut_cS4J5wPv9ANtT5Ep1deF4kxhe-G7L47JeWCSq4B2kFtLGOZI_HWIPXfjkFaDgmJ5cfQ_m1XoEbTpaOI02DoDyVuifvHJq85vtAdPsEybVw8VTwzfP9x2zyRP5Vo-OA7xkG4eGlUwEMssgMX3Pphn__5AGcUIgUVIDmI8S7mlKlgMQsgVOEcadqUiX-ZPPQSyKH5UzUKhPyT_rH5QdM4qLpu6e6Ykuw8Bew5asbbEVxFwyK526ZuxEotrzmuvbYQ0Ou95GAqH0VyTz7itLIhX3Xa4oe-hCUEIR_9UdsmVHKJGK9hyGpHe8dRAZRaEI64auEK_HzYI8Z8-PTa57hYziiMvDBnnSudRXbQtUmzmlMnuckAkxGgnNdFmn6YgamDAdaxjNBdI-Dv8RxT6EqhKQKcG8M187QltxiIfbdzsKTAx-dDAjSUU64gSTUhzfy8NoBxkS-WL9HynQUr1pfKUhsCEdLHM8N5nOWtIFZAb4OK7b8qtF1GtBZxzD1wI-VBUBREVUrA_qS8fzxIs_r_bNCvSMUn2Z3EMB4KPkgSRkDAoHzjzYbkI5i-htACEJnZzXVYA-w97ZkbzD9E0yVJJmXTXIfSgT1Eh22CUOzRHVg7L5c4OLkiMBNOKnmO5fZcxZyYgLvS4l3HBgooM07WwHc76488l5iJUslqr1m1Ab5o7d66HsLxJO63KX1YaNjyhBzDFpVgCjKxZRwqBtMCQfeR45j8t-i8nBllBX7bd7dWJcY9bZzqMXmaMChAj7y7yunExSEgIFDIhaiuQ4hvRJVWcFa8SsZ551-4o883764",cRq: {ru: 'aHR0cHM6Ly93d3cucGVycGxleGl0eS5haS9zb2NrZXQuaW8vP0VJTz00JnRyYW5zcG9ydD1wb2xsaW5nJnQ9MzllZTQ3ZTI=',ra: 'TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzExNS4wLjAuMCBTYWZhcmkvNTM3LjM2',rm: 'R0VU',d: 'K7O49N1gCDDt5yhI5XXg0BISxqQKWN8jiMKxlp2sLqDzegNdDd6db9SIf7hpNEACbLpLngDn0A/HsGrIbgwJa+F6w0Tp4VEQ71l4/thVpi0bdZT6Lmopw3XewHFr8XP29p6HNnQYTJwQxGiHGdnhFIKhUY0JhZBKMDMNi3BzeE8F4kuJTq8dZ1ch12h0TExWgDWseYI4mj2UNGIbXVi/xnh2OjLUz3PTI35N56YszaIxrZ8pELHrXgO4Xe1e/U/jhYEggriXv/M+2bNYP6+69Wr79PlGVDtz/McYf4orJKcC6qi1h84YY+2Qtm6BnC1RJh7NMn0y4AzZlF4Fgm9+6idXNEy2/URI9Ltgul2SVCAt3UYwQKa/Z7c28T0xebiYom5AsatbtyQxFak+u1UQu4RHmbDlOY+HN27JVjBuDhbEEPf1YfndG+QwTAJ59pxV+vIZ+napZ7JJnEqnpJ7rKhsXxXZlk/QeyG8dV0EzCu0Mdy48hdz6tHocBPSHwsjQ/ICVOTWlJ7teWVGAXzbxB/+H4DFWkDUAIgeTRRIOfy3PetocAkVmbah9b+EEHlSf',t: 'MTY5NTEyNzg0Ni4wMzUwMDA=',cT: Math.floor(Date.now() / 1000),m: 'piVVtgeKBrJfE7jTJGXP9lAeyP/RzNW1736YFmkrA/s=',i1: '1NveZeysLRHYsPkW28bCag==',i2: 'KSYc46w6KeyVCjN40aIbJg==',zh: 'NU8ixJjbvuzjjI0VYVlScfuo4FsYASw7wpJI5etvkPw=',uh: 't4+sYN7BT87gxptd9nEHs9sipyUVut9BGxqO8owsoq4=',hh: 'Y4wbTy2+H//SzqXCr/ut8Fn8eNgcrMRWkXlJV1vMwRU=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=8091f4cdb85254db';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/socket.io\/?EIO=4&transport=polling&t=39ee47e2&__cf_chl_rt_tk=gU9S_66tXTTpluU4PM.qJJPFloDJ3sHCOgiuL4.D3NQ-1695127846-0-gaNycGzNEJA" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v8b253dfea2ab4077af8c6f58422dfbfd1689876627854" integrity="sha512-bjgnUKX4azu3dLTVtie9u6TKqgx29RBwfj3QXYt5EKfWM/9hPSAI/4qcV5NACjwAo8UtTeWefx6Zq5PHcMm7Tg==" data-cf-beacon='{"rayId":"8091f4cdb85254db","version":"2023.8.0","b":1,"token":"92730c73a9e747fbb6a25e1d6657122d","si":100}' crossorigin="anonymous"></script>
</body></html>` but if you open it in a webbrowser (safari) '0{"sid":"NgoDnUXtvwaOK1xmAWmg","upgrades":["websocket"],"pingTimeout":20000,"pingInterval":25000}'
