### ISSUE TITLE
Exception has occurred: WebSocketConnectionClosedException socket is already closed.

### ISSUE THREAD

**Issue by lixiaochuan2020** [helallao/perplexity-ai#18]

**Comment by lixiaochuan2020** [comment]
#### I download this github storehouse, and get both cookies and headers just as README taught me, but I got an error called "Exception has occurred: WebSocketConnectionClosedException", and details are "socket is already closed." I don't know why this happended, because I have used the latest cookies and headers.
#### This is my first issue on github, if there exists any mistakes, please let me know and I will improve them

**Comment by lixiaochuan2020** [comment]
<img width="714" alt="CleanShot 2023-09-19 at 10 04 55@2x" src="https://github.com/helallao/perplexity-ai/assets/83334710/43d801db-d41b-4371-a181-e6073030305d">

[](url)

**Comment by helallao** [comment]
Works for me, follow the steps properly
![image](https://github.com/helallao/perplexity-ai/assets/78656003/1324fc1d-1b80-4925-8ac1-43aad7274729)
