### ISSUE TITLE
Would it be possible to automatically update the header/cookies via Selenium WebDriver?

### ISSUE THREAD

**Issue by Dima-369** [helallao/perplexity-ai#2]
First of all, thanks for this. This works quite well, but I often get the error that the tokens are expired. Is there a way to also automate that? The user still has to manually bypass Cloudflare with clicks, but it would make updating the tokens a lot easier.

**Comment by helallao** [comment]
it's possible but an easier way is that creating multiple accounts before your tokens get expired, so you will still be connected to them via websocket connections, even your tokens get expired.

**Comment by Dima-369** [comment]
Ah, I understand now. I modified `perplexity.py` slightly to always exit after outputting the answer since I rarely run it and I usually only need a single answer when I invoke it from an external application.

By exiting, the websocket connection is simply not kept alive and I can't benefit from that. I also did not fill in `emailnator_headers` and `emailnator_cookies`. I suppose that is the issue for me here.

**Comment by bacladjan-corp** [comment]
could you please share the modified code if you don't mind?

**Comment by Dima-369** [comment]
> could you please share the modified code if you don't mind?

I just checked again and I, in fact, did not modify `perplexity.py`, but I close the websocket after `.search()` like this:

```json
print(perplexity_cli.search('Your query here', mode='copilot', focus='internet'))
perplexity_cli.ws.close()
```

Then the script exits after answering.

**Comment by bacladjan-corp** [comment]
thank you very much, and as I understand I will have to update the cookie list sometimes ?

**Comment by Dima-369** [comment]
> thank you very much, and as I understand I will have to update the cookie list sometimes ?

Yes, study the README, it has all the info.
