### ISSUE TITLE
Followup after file upload losing context

### ISSUE THREAD

**Issue by dallecki** [helallao/perplexity-ai#22]
I'm running the task on perplexity webpage with the file :
1. Question on perplexity.ai :
![www_question](https://github.com/helallao/perplexity-ai/assets/93999901/bb3cb8bf-b6da-412b-9dcb-7d47fc985c74)

2. Followup  has the same file as a source:
![www_followup](https://github.com/helallao/perplexity-ai/assets/93999901/498bbd12-7670-41e1-bac5-e53cb7562fbc)

Next, I'm running the code with streamlit and asking the same question and followup on the same file:
```
backend_uuid = None
first_query = st.session_state.last_perplexity_response is None
if not first_query: 
    backend_uuid = st.session_state.last_perplexity_response['backend_uuid']
if first_query:
    my_file = (open('apple_cake.txt', 'rb').read(), 'txt')
    perplexity_response = st.session_state.perplexity_cli.search(prompt, mode='concise', file = my_file)
else: 
    perplexity_response = st.session_state.perplexity_cli.search(prompt, mode='concise', follow_up = backend_uuid)
bot_response = perplexity_response['text']['answer']
st.session_state.last_perplexity_response = perplexity_response
```
1. Question on perplexity.ai:
![wrapper_question](https://github.com/helallao/perplexity-ai/assets/93999901/774363c2-9be8-4a06-b899-15f1e162c866)

2. Followup on perplexity.ai is not using the file as a source:
![wrapper_followup](https://github.com/helallao/perplexity-ai/assets/93999901/bfafa03a-a01b-4f03-bafb-75a0cf0735b8)

**Comment by helallao** [comment]
I made some changes with last update. But i'm not really sure if it is fixed indeed. By the way you can upload multiple files at once now. Please read new [readme](../#how-to-use) and reply me if it's fixed or not.

**Comment by dallecki** [comment]
It's fixed. Thanks a lot.
