### ISSUE TITLE
Can't seems to contact with Perplexity

### ISSUE THREAD

**Issue by jerry048** [helallao/perplexity-ai#28]
### Environment:
Python 3.11
<html>
<body>

Package | Version| 
-- | -- | 
aiohttp | 3.8.6 | 
aiosignal | 1.3.1 | 
async-timeout | 4.0.3 | 
attrs | 23.1.0 | 
beautifulsoup4 | 4.12.2 | 
bs4 | 0.0.1 | 
certifi | 2023.7.22 | 
charset-normalizer | 3.3.1 |
frozenlist | 1.4.0 |
idna | 3.4 |
lxml | 4.9.3 |
lxml-stubs | 0.4.0 |
multidict | 6.0.4 |
pip | 23.3.1 |
requests | 2.31.0 |
requests-toolbelt | 1.0.0 |
setuptools | 68.2.2 |
soupsieve | 2.5 |
urllib3 | 2.0.7 |
websocket-client | 1.6.4 | 
wheel | 0.41.2 | 
yarl | 1.9.2 | 

</body>
</html>

### Problem
I've encountered an issue while using both the async and normal methods. Despite my efforts, I'm not receiving any return. I've ensured that the cookie is correctly obtained and placed, and I've followed the methods outlined in the [READ.me](https://github.com/helallao/perplexity-ai#how-to-get-the-cookies) and in Issue #4.
Upon further investigation, I've found that the email is successfully created and a registration confirmation is received. However, the code seems to hang at `while not self._last_file_upload_info:
                    pass`, failing to get the upload URL for the file. If no file is attached, the code gets stuck at `while True: while not self._last_answer: pass`.
I'm seeking insight into why this might be happening. Can you replicate this issue on your end? I appreciate your assistance.

**Comment by helallao** [comment]
It's working on my end, try to update all of your libraries, it's hard to find which one is causing problem. Here are my owns:

Python 3.11.3
Package| Version
:---: | :---:
‎a | a

**Comment by thanhtamns** [comment]
@jerry048  Have you solved this problem yet? I also encountered the same problem as yours.
Is there any way to fix it? @helallao I also have versions similar to yours.
