### ISSUE TITLE
It sometimes says "Shard ID None heartbeat blocked for more than x seconds

### ISSUE THREAD

**Issue by CutyCat2000** [helallao/perplexity-ai#29]
![image](https://github.com/helallao/perplexity-ai/assets/132785498/13b98cff-1575-49c6-bbc2-425f24db5311)
Can you fix this?

**Comment by helallao** [comment]
Hi, it looks like perplexity_async.py breaking connection of discord.py because of while loop in line 304, i changed codes to asynchronous sleep until perplexity.ai responds. Use new perplexity_async.py and reopen this issue if it happens again.
