### ISSUE TITLE
Error while hosting

### ISSUE THREAD

**Issue by bacladjan-corp** [helallao/perplexity-ai#3]
I wanted to send a bot with this api to the server, but it gives an error:
HTTPSConnectionPool(host='[www.perplexity.ai](https://www.perplexity.ai/)', port=443): Max retries exceeded with url: [/search](tg://bot_command?command=search)[/dc2e0bc5](tg://bot_command?command=dc2e0bc5)-4518-49a4-9a9c-2af9a1e10523 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

can you tell me how to fix it please?

**Comment by helallao** [comment]
Looks like you're trying to use your cookies on another ip address, which only works on ip address that you used to bypass cloudflare's captcha.
