### ISSUE TITLE
AssertionError at line 99 in file perplexity.py

### ISSUE THREAD

**Issue by sergiosemenukha** [helallao/perplexity-ai#31]
Hi there!
I'm using your module with my own credentials (I got PRO account) and since today I'm getting AssertionError upon client initialization at [this](https://github.com/helallao/perplexity-ai/blob/044526329a62aeeff276f22f7a6fadbfd393ab22/perplexity.py#L99C22-L99C22) point . 

Looks like this happens because of CloudFlare. Any ideas?

**Comment by sergiosemenukha** [comment]
Again started working after I obtained new cookies and headers.

**Comment by helallao** [comment]
If you got PRO account  and want to use it, then look at issue #4. Also change copilot and file_upload values at [line 94](https://github.com/helallao/perplexity-ai/blob/main/perplexity.py#L94) manually to not cause assertion errors.
