### ISSUE TITLE
"json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)" when running labs_cli.ask

### ISSUE THREAD

**Issue by drimeF0** [helallao/perplexity-ai#33]
code:

```py
import perplexity

labs_cli = perplexity.LabsClient()

# model = ['pplx-7b-online', 'pplx-70b-online', 'pplx-7b-chat', 'pplx-70b-chat', 'mistral-7b-instruct', 'codellama-34b-instruct', 'llama-2-70b-chat', 'llava-7b-chat', 'mixtral-8x7b-instruct', 'mistral-medium']
print(labs_cli.ask('hi', model='mixtral-8x7b-instruct'))
```

error:
```py
Traceback (most recent call last):
  File "c:/Users/drime/Documents/drimef0_projects/koboldai_characters/samplers/sampler_perplexity.py", line 3, in <module>
    labs_cli = perplexity.LabsClient()
  File "c:\Users\drime\Documents\drimef0_projects\characters_bot\samplers\perplexity.py", line 409, 
in __init__
    self.sid = json.loads(self.session.get(f'https://labs-api.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}').text[1:])['sid']
  File "C:\Users\drime\.pyenv\pyenv-win\versions\3.8.9\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\drime\.pyenv\pyenv-win\versions\3.8.9\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())     
  File "C:\Users\drime\.pyenv\pyenv-win\versions\3.8.9\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

`self.session.get(f'https://labs-api.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}').text[1:]` returns this:

```
!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/cdn-cgi/styles/challenges.css" 
rel="stylesheet"><meta http-equiv="refresh" content="375"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span class="icon-wrapper"><div class="heading-icon warning-icon"></div></span><span id="challenge-error-text">Enable JavaScript and cookies 
to continue</span></div></div></noscript></div></div><script>....................................................................
```

The request seems to be blocked

**Comment by drimeF0** [comment]
I've created a pull request to fix this bug. In addition, I've expanded the functionality of LabsClient a bit: #34

**Comment by helallao** [comment]
Thank you so much for your time and work <3.

**Comment by thanhtamns** [comment]
It seems this error still occurs. I also got this error even when using @drimeF0 code

**Comment by thanhtamns** [comment]
I also get this error:

Exception has occurred: AssertionError
exception: no description
  File "F:\***\***\perplexity-ai\perplexity.py", line 216, in __init__
    assert self.session.post(f'https://labs-api.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}&sid={self.sid}', data='40{"jwt":"anonymous-ask-user"}').text == 'OK'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\*****\*****\perplexity-ai\run_labs.py", line 35, in <module>
    labs_cli = perplexity.LabsClient(headers, cookies)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError:

**Comment by helallao** [comment]
You're probably using wrong cookies

https://github.com/helallao/perplexity-ai/assets/78656003/79d391c2-6971-4178-b1fb-892c5cc66696

**Comment by thanhtamns** [comment]
Thanks for guide. 
This error now appears more frequently in Client code as well. I'm looking for ways to improve it but there always seem to be problems with websocket. 
And it seems that the value at **self._last_answer** will be None when done with multiple consecutive run.
![image](https://github.com/helallao/perplexity-ai/assets/14258304/9b483e4d-e98d-4535-96f3-c52d474b7f8c)

**Comment by thanhtamns** [comment]
And I'm sure I'm not misusing cookies

**Comment by thanhtamns** [comment]
> Same issue.
> 
> I made a [Node.js version](https://github.com/rgomezp/perplexity-sdk) for those interested

But your code is official API. Not like this ...

**Comment by rgomezp** [comment]
> > Same issue.
> > I made a [Node.js version](https://github.com/rgomezp/perplexity-sdk) for those interested
> 
> But your code is official API. Not like this ...

It doesn't generate unlimited copilots yet, but maybe soon!
