### ISSUE TITLE
How to use claude2/gpt4

### ISSUE THREAD

**Issue by thanhtamns** [helallao/perplexity-ai#35]
Hi Mate,
How can I use only Claude2/GPT4 in all my queries?
Is there a way to turn the Copilot function on or off?

**Comment by helallao** [comment]
Actually i don't know how to use them because i don't have a pro account.

**Comment by helallao** [comment]
I would appreciate if somebody got pro account dm me in discord to help me code it. Discord: `nightmare#3887

**Comment by 14790897** [comment]
I can borrow you my pro account(don't worry, this account I got if for free). liuweiqing2@liuweiqing.top
![image](https://github.com/helallao/perplexity-ai/assets/121866954/e88bc708-64b9-43d9-bbaf-84d79949c079)

**Comment by helallao** [comment]
Updated the codes, thank you so much.
