### ISSUE TITLE
How to use it with an registered perplexity account?

### ISSUE THREAD

**Issue by phamxtien** [helallao/perplexity-ai#4]
Please guide.
Not use temp mail

**Comment by helallao** [comment]
Open [Perplexity.ai](https://perplexity.ai/) website. Sign in to your account if you're not signed in. Click F12 or Ctrl + Shift + I to open inspector. Check "Preserve log" button, go to the "Network" tab in the inspector, click the "clear" button in inspector (image 1), click refresh button in your browser, right click the first request in the Network Tab and hover on "Copy" and click to "Copy as cURL (bash)". Now go to the [curlconverter](https://curlconverter.com/python/), paste your code here. The header and cookies dictionary will appear, copy them and use in your codes as "perplexity_headers" and "perplexity_cookies".

![image](https://github.com/helallao/perplexity-ai/assets/78656003/20203a0c-04e4-4394-8e8a-6dc84f9c9f8e)

![image](https://github.com/helallao/perplexity-ai/assets/78656003/0ce64fa5-0c98-4cfc-b67d-a9120d852db6)

Do not call "perplexity_cli.create_account" function in your script, these cookies will cause the client to use your account, and they are temporary as others.
