### ISSUE TITLE
Is this still working? 

### ISSUE THREAD

**Issue by deorc-unity** [helallao/perplexity-ai#40]
I found some errors: 
File : perplexity.py
Line 525: new_account = Client(perplexity_headers,perplexity_cookies)
Line 526: new_account.create_account(emailnator_headers,emailnator_cookies)
These lines are missing 'self' keywords in the Client & create_account parameters. 

The myfile.txt & myfile2.pdf are storing the account information but what are these files trying to store initially?

I am facing this error: 'Error: Handshake status 403 Forbidden'

**Comment by helallao** [comment]
Repository updated
